/**
 *
 * $Id$
 */
package statechart.validation;

import org.eclipse.emf.common.util.EList;

import statechart.Node;
import statechart.Transition;
import statechart.Variable;

/**
 * A sample validator interface for {@link statechart.Model}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateNodes(EList<Node> value);
	boolean validateTransitions(EList<Transition> value);
	boolean validateVariables(EList<Variable> value);
	boolean validateDescription(String value);
	boolean validateMetadata(String value);
}
